server:
  port: 8085
spring:
  application:
    name: simple-feign-with-hystrix
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    #    注册中心地址
    service-url:
      defaultZone: http://lixy:Ml06200818@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
#hystrix默认超时时间  默认1s
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 2000
#feign日志
logging:
  level:
    com.lixy.simple.feign.consumer.api.UserClient: debug

#第二种负载模式 这种模式优先级最高
#ribbon需要负载的微服务名称
simple-ribbon-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
        exclude: ''
  endpoint:
    health:
      show-details: always
feign:
  hystrix:
    enabled: true