spring:
  application:
    name: simple-ribbon-consumer
server:
  port: 8082
eureka:
  client:
#    注册中心地址
    service-url:
      defaultZone: http://lixy:Ml06200818@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}