spring:
  security:
    user:
      name: lixy
      password: Ml06200818
---
spring:
  profiles: peer1
  application:
    name: eureka-peer
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
  #注册中心地址
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8762/eureka/
---
spring:
  profiles: peer2
  application:
    name: eureka-peer
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    #注册中心地址
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8761/eureka/
